### ISSUE TITLE
Where is the dll file?

### ISSUE THREAD

**Issue by echavez-eb** [freemansoft/jacob-project#24]
I need the JAR and DLL files.
Followed all steps to run the build from this page
`https://github.com/freemansoft/jacob-project/blob/main/docs/BuildingJacobFromSource.md`
Selected **ANT default** build because in **BuildingJacobFromSource.md**:
**ant default** executes the following steps when using the default target.

- Build the Java code
- Build the jni code
- _create the dll
- create jar file_

JAR file is created here: /jacob-project-main/release/java/jacob.jar
**_But there is not sign of the DLL file._**

**Where is it?**

**Comment by SedateC** [comment]
![image](https://user-images.githubusercontent.com/7529801/191644332-78a12d44-6e38-4ead-b544-1b7dbb64f248.png)

**Comment by jeff-1984** [comment]
Hello, sorry but I don't see neither where to find the DLLs, how do you get to that Assets page ?

**Comment by jeff-1984** [comment]
Ok found it : https://github.com/freemansoft/jacob-project/releases

**Comment by ZiHollow** [comment]
> Ok found it : https://github.com/freemansoft/jacob-project/releases

Thank you!!!

**Comment by freemansoft** [comment]
Back to the original question.  When running the build, the  .dll should end up; in the release dir in a directory called x64.

**Comment by jjlauer** [comment]
Built a simple project that helps publish jars of the native code and extracts it at runtime. https://github.com/fizzed/jacob
