### ISSUE TITLE
hi, is there maven pom.xml

### ISSUE THREAD

**Issue by liming1010** [freemansoft/jacob-project#3]
hi, is there maven pom.xml

**Comment by freemansoft** [comment]
This project does not exist in any of the maven repositories.  
This has been a common request but no one has done the work.

Is that what you are asking?

**Comment by muhdkhokhar** [comment]
<dependency>
    <groupId>com.hynnet</groupId>
    <artifactId>jacob</artifactId>
    <version>1.18</version>
</dependency>

**Comment by freemansoft** [comment]
Sorry I still don't understand.

**Comment by muhdkhokhar** [comment]
> 
> <dependency>
>     <groupId>com.hynnet</groupId>
>     <artifactId>jacob</artifactId>
>     <version>1.18</version>
> </dependency>
>

**Comment by muhdkhokhar** [comment]
https://mvnrepository.com/artifact/com.hynnet/jacob

**Comment by liming1010** [comment]
ok
