### ISSUE TITLE
Incorrect delete in Dispatch JNI invokev()

### ISSUE THREAD

**Issue by EJP286CRSKW** [freemansoft/jacob-project#40]
In the error handling case at the end of the method we have:
````
buf = CreateErrorMsgFromInfo(hr, &excepInfo, nm);
````
and
````
dispIdAsName = new char[256];
````
and later:
````
if (buf) delete buf;
if (dispIdAsName) delete dispIdAsName;
````
The latter should be:
````
delete[] buf;
delete[] dispIdAsName;
````
to agree with how they were created, as `new wchar_t[...]` and `new char[...]` respectively.
The null tests are unnecessary.

**Comment by EJP286CRSKW** [comment]
Actually `dispIdAsName` could be declared as `char dispIdAsName[256];` to avoid the `delete []` altogether.

**Comment by freemansoft** [comment]
Is this what you are saying

1. The null check on `if (buf) delete buf` is unecessary because it gets allocated on both paths.
1. The order should be flipped so that they are released in the inverse order they were created.

**Comment by EJP286CRSKW** [comment]
For clarity, the problems here are:

1. `delete` should be `delete[]` in both cases.
2.  The null tests are redundant in both cases.

**Comment by freemansoft** [comment]
https://github.com/freemansoft/jacob-project/commit/8e4472e2a5af9a3646685b25b936411bd55c0e9f
