### ISSUE TITLE
Release 2.0 will be compiled against Java 17 and drop 32bit dll support.

### ISSUE THREAD

**Issue by freemansoft** [freemansoft/jacob-project#55]
Never anticipated doing another release 20 years after I took this over from the original author because I needed a patch for a contract job. 
The primary goal of a possible future release would be

1. Pick up memory leak fixes
2. Maybe publish to a maven repo for the first time in 20 years.

Side effects of any changes 

1. Move from Java 8 to Java 17
2. Drop 32 bit dll support.  
3. Drop 32 bit JVM support.
4. Code formatted using VSCode instead of Visual Studio orr Eclipse.
6. Build using the ANT bundled with the VS Code plugin.
7. Moving to the latest Windows SDK 10.22621.0
8. Drop any information around Eclipse.  I'll do any Java work in VSCode or IntelliJ

**Comment by freemansoft** [comment]
Will not be making this change at this time due to developer request

**Comment by zspitzer** [comment]
are the first two action items still planned?
